# Generated by Django 5.0.3 on 2024-05-06 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_backend', '0002_movie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=8, unique=True)),
                ('booking_date', models.DateField()),
                ('booking_time', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('booking_qr', models.FileField(blank=True, null=True, upload_to='booking_qr/')),
                ('booking_pdf', models.FileField(blank=True, null=True, upload_to='booking_pdfs/')),
                ('show_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, default=180.0, max_digits=6)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication_backend.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
