# Generated by Django 5.0.3 on 2024-05-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_backend', '0003_bookingregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingregister',
            name='show_date',
            field=models.CharField(max_length=10),
        ),
    ]
