# Generated by Django 5.0.3 on 2024-05-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_backend', '0004_alter_bookingregister_show_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingregister',
            name='moviename',
            field=models.CharField(default='', max_length=20),
        ),
    ]
