# Generated by Django 5.0.3 on 2024-05-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_backend', '0006_alter_movie_show_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Show_time',
            new_name='Show_timeOne',
        ),
        migrations.AddField(
            model_name='movie',
            name='Show_timeThree',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='Show_timeTwo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
