# Generated by Django 5.0.3 on 2024-05-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_backend', '0007_rename_show_time_movie_show_timeone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingregister',
            name='moviename',
            field=models.CharField(default='', max_length=40),
        ),
    ]
