# Generated by Django 5.0.3 on 2024-05-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_backend', '0009_movie_show_dateone_movie_show_datethree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingregister',
            name='booking_qr',
        ),
        migrations.AddField(
            model_name='bookingregister',
            name='booked_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
