# Generated by Django 5.0.3 on 2024-05-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_backend', '0010_remove_bookingregister_booking_qr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingregister',
            name='booking_pdf',
        ),
    ]
